chore: update scripts

diff --git a/src/script/zfs-create-log b/src/script/zfs-create-log
--- a/src/script/zfs-create-log
+++ b/src/script/zfs-create-log
@@ -1,15 +1,18 @@
 #!/bin/sh
 set -eo pipefail
 
-fs_name="data/log"
-mount_name="/data/log"
-log_path="/var/log"
+if [[ -z "$1" ]]; then
+  echo "Usage: $0 <pool_name>"
+  exit 1
+fi
+
+pool_name="$1"
+fs_name="${pool_name}/log"
 
 echo ==================== OpenZFS 创建文件系统 ${fs_name} ====================
 
-
-if [[ -d "/${fs_name}" ]]; then
-  echo "Directory exists: /${fs_name}"
+if ! zpool list "$pool_name" &>/dev/null; then
+  echo "Error: zfs pool '$pool_name' not found!"
   exit 1
 fi
 
